/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_kamfat_omengo_util_JniUtil */

#ifndef _Included_net_kamfat_omengo_util_JniUtil
#define _Included_net_kamfat_omengo_util_JniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_kamfat_omengo_util_JniUtil
 * Method:    test
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_kamfat_omengo_util_JniUtil_test
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
